name: 'Python wheels manylinux build'
description: 'Build manylinux wheels'
inputs:
  python-versions:
    description: 'Python versions to target, space-separated'
    required: true
    default: 'cp37-cp37m cp38-cp38'
runs:
  using: 'docker'
  image: 'Dockerfile'
  env:
    PLAT: 'manylinux1_x86_64'
  entrypoint: '/build-manylinux.sh'
  args:
    - ${{ inputs.python-versions }}
branding:
  icon: 'package'
  color: 'green'
