name: Test in manylinux

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.5, 3.6, 3.7, 3.8 ]
    env:
      PYTHON: python${{ matrix.python-version }}
    steps:
    - uses: actions/checkout@v1
    - name: Install test deps
      run: |
        python -m pip install --upgrade setuptools wheel pip
        pip install unidic-lite ipadic pytest
    - name: Run tests
      run: |
        pytest 
